#!/bin/sh

## Files and cmd
EWW="~/.local/bin/eww/eww"
CFG="$HOME/.config/eww/zura/eww-bar/"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
        top_bar \
        
}

## Launch or close widgets accordingly
run_eww
