#!/usr/bin/bash

## Files and Directories
DIR="$HOME/.config/i3/polybar/cristina/"
SFILE="$DIR/system"
RFILE="$DIR/.system"
MFILE="$DIR/.module"
##export MPD_HOST=$HOME/.mpd/socket
## Get system variable values for various modules
get_values() {
	ADAPTER=$(upower -i `upower -e | grep 'AC'` | grep 'native-path' | cut -d':' -f2 | tr -d '[:blank:]')
	INTERFACE=$(ip link | awk '/state UP/ {print $2}' | tr -d :)
}

## Write values to `system` file
set_values() {
	if [[ "$ADAPTER" ]]; then
		sed -i -e "s/sys_adapter = .*/sys_adapter = $ADAPTER/g" 						${SFILE}
	fi
	if [[ "$INTERFACE" ]]; then
		sed -i -e "s/sys_network_interface = .*/sys_network_interface = $INTERFACE/g" 	${SFILE}
	fi
}

## Launch Polybar with selected style
launch_bar() {
	INTERFACE=$(ip link | awk '/state UP/ {print $2}' | tr -d :)

	if [[ ! -f "$MFILE" ]]; then
		if [[ "$INTERFACE" == e* ]]; then
			sed -i -e 's/network/ethernet/g' "$DIR"/config
		fi
		touch "$MFILE"
	fi
		
  sh $DIR/Theme.sh
}

# Execute functions
if [[ ! -f "$RFILE" ]]; then
	get_values
	set_values
	touch ${RFILE}
fi

export_vars() {
  export PATH=$PATH:~/.config/i3/scripts/
}

launch_bar
export_vars
